Revert "orangepi5+: skip perf only in sdImage"
This reverts commit 7315cbaaace89cfaf12303484ca4bfb141e05c65.

    builder for '/nix/store/863lc3ir4ahpxzq6bcjv940xzkbbc04m-perf-linux-aarch64-unknown-linux-gnu-6.8.0.drv' failed with exit code 2;
    last 10 log lines:
    >   149 | #if defined(LIBTRACEEVENT_VERSION) &&  LIBTRACEEVENT_VERSION >= MAKE_LIBTRACEEVENT_VERSION(1, 5, 0)
    >       |                                                              ^~
    > error: command '/nix/store/ffi9k9y0w3sydgp2nk3q1pk0qq02rkb0-aarch64-unknown-linux-gnu-gcc-wrapper-12.3.0/bin/aarch64-unknown-linux-gnu-cc' failed wit>
    >   LD      /build/source/tools/perf/libbpf/staticobjs/libbpf-in.o
    > cp: cannot stat 'python_ext_build/lib/perf*.so': No such file or directory
    > make[2]: *** [Makefile.perf:678: python/perf.cpython-311-aarch64-linux-gnu.so] Error 1
    > make[2]: *** Waiting for unfinished jobs....
    >   LINK    /build/source/tools/perf/libbpf/libbpf.a
    > make[1]: *** [Makefile.perf:261: sub-make] Error 2
    > make: *** [Makefile:70: all] Error 2